### ISSUE TITLE
Playground fails to build on Node 13

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/sdkgen#1] opened 2020-02-08 12:41 UTC
See https://github.com/sdkgen/sdkgen/runs/433452998?check_suite_focus=true for details.

Some dependency is installing `sharp` and it seems to not support Node 13 yet? Upgrading to latest version should solve the problem: https://github.com/lovell/sharp/issues/1909

**Comment by kevinoliveira** [comment] 2020-10-06 01:40
@lbguilherme the pull request above is now merged, the issue is resolved.

**Closed** 2020-10-06 11:29 UTC
Labels: bug
